### ISSUE TITLE
Dockerize react app

### ISSUE THREAD

**Issue by tatysheva** [tatysheva/todo-React#1]
I need someone to wrap my react application into a docker container. The application should run via command ``` docker run ```.

**Comment by marnixbouhuis** [comment]
Hi @tatysheva

I'm able to dockerize this app, I'll use NGINX as a base and configure is so it redirects all traffic to index.html. This allows you to use stuff like react-router.

Can you assign me?

**Comment by Zoxon470** [comment]
Hello @tatysheva I can dockerize your app and configure NGINX. I can do it faster than @MarnixBouhuis

**Comment by marnixbouhuis** [comment]
Dude, in programmer culture this is considerd a dick move

![image](https://user-images.githubusercontent.com/10454703/95024919-536d7a00-0686-11eb-9870-f8956d5848ad.png)

**Comment by Zoxon470** [comment]
@MarnixBouhuis Bro it's business, it's IT business. Sho me your code via docker.

**Comment by marnixbouhuis** [comment]
Sorry man, just wanted to help the OS community. If this is so important for you you can have this issue, I don't care. I do this in my spare time, I do not make money from contributing to open source projects.
No need to be toxic.

**Comment by Zoxon470** [comment]
@MarnixBouhuis Bro, it's joke, don't worry please. I'm just kidding, IT is boring.

**Comment by Zoxon470** [comment]
@tatysheva Thanks! I will do as soon as possible.

**Comment by Zoxon470** [comment]
@tatysheva I have done. See PR - https://github.com/tatysheva/todo-React/pull/2
